server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/pabloabaldiez/microservicios.git
          search-paths: config_data
  application:
    name: config_service
