server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/pabloabaldiez/microservicios
          search-paths: config-data
  application:
    name: config-service